name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Create screeps.json
        run: |
          cat <<'INNER_EOF' > screeps.json
          {
            "main": {
              "token": "${{ secrets.SCREEPS_TOKEN }}",
              "protocol": "https",
              "hostname": "screeps.com",
              "port": 443,
              "path": "/",
              "branch": "main"
            }
          }
          INNER_EOF
      - name: Deploy to Screeps
        run: npm run push-main
